name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ':rocket: Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: ':bug: Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: ':wrench: Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '<>"&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
