name: Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 'stable'

      - name: Cache Nimble packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
            ~/.cache/nim
          key: ${{ runner.os }}-nimble-${{ hashFiles('**/nimble.lock') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - name: Install dependencies
        run: nimble install -d --accept

      - name: Run tests
        run: nimble test