name: Test and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: nimble install -d --accept
      - name: Run tests
        run: nimble test
      - name: Draft release
        if: github.ref == 'refs/heads/main'
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
      - uses: actions/checkout@v4
      - name: Publish Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
